language: perl
cache:
  - local
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
    - "cpanm Carton"
install:
    - "carton install"
script: "make test"
