language: perl
cache:
  - local
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
    - "cpanm Carton"
install:
    - "carton install"
before_script:
    - mysql -uroot -e "CREATE DATABASE test DEFAULT CHARSET=utf8";
    - mysql -uroot -e "GRANT ALL PRIVILEGES ON test.* TO 'testuser'@'localhost' IDENTIFIED BY 'testpass'"
script: "make test"
